### ISSUE TITLE
WCT2 seems cannot transfer styles without segmentation maps? Could you please indicate how to make it works without segmentation maps since you claimed in your paper that it supports transfer directly and without segmentation.

### ISSUE THREAD

**Issue by pkuanjie** [clovaai/WCT2#10]

**Comment by jaejun-yoo** [comment]
Dear Richard An,
Thank you for reading our paper. One thing I want to be clear is that we did not argue that we can remove the necessity of the segmentation label map. We removed the "post-processing" steps, which was used in the previous methods to correct the spatial distortions due to their network architecture. We even noted this limitation as a future work at the end of the conclusion. 
However, the issue you raised is actually very sharp. This is the problem we need to solve. The reviewers mentioned that as well, and we will make the failure scenario clearer in the camera-ready version of the paper. 
On the other hand, if you want better stylization, I would recommend using the "sum-ver" of the network, which is more theoretically sound or adding other tricks, such as decoder stylization and multi-level stylization (Fig. 9). 
Best,
Jaejun
