### ISSUE TITLE
Some questiona about network?

### ISSUE THREAD

**Issue by xuzhongyou** [clovaai/WCT2#12]
Thank you for your good job ! I have a problem that the photowct-network had not used the raw picture and it yield some error points. what it will be if we add some raw information like unet structure? Does the 'unet' idea success or the haar wavelet works?

**Comment by youngjung** [comment]
Hi xuzhongyou,
Could you explain meaning of
* raw picture
* error points
* raw information?

Sorry I don't quite get it right away.

**Comment by xuzhongyou** [comment]
> Hi xuzhongyou,
> Could you explain meaning of
> 
> * raw picture
> * error points
> * raw information?
> 
> Sorry I don't quite get it right away.

sorry for not clear. the raw picture and raw information i mean the skip operation added in the network which has not appeared in photowct-decoder ? Your good jod solves the error points without smooth process, but i don't know the skip connetcion works or the haar wavelet ? I hope i made myself clear.

**Comment by jaejun-yoo** [comment]
Dear @xuzhongyou 
Hi. Thank you for your interest on our project! Regarding your question, I think the analysis section of our paper provides the answer. It shows that the other pooling function does not provide good results as Haar wavelets does, which means that the other pooling methods (e.g., fixed and learnable) did not work well even with the skipped connection. (Please note that we treated the other poolings equally to the wavelet pooling so that they have skipped connections.) 
I hope this would help your understanding.

---
If you find this project is useful or interesting, please consider ⭐️ and watch our repo. Thanks!

**Comment by xuzhongyou** [comment]
Thank u, i helps me a lot.
