### ISSUE TITLE
Segmentation maps precision

### ISSUE THREAD

**Issue by Angtrim** [clovaai/WCT2#15]
I'm trying to use the net to transfer the style of a mountain landscape photo to another.
I tried building a coarse segmentation map for the 2 photos, but the result is off (see attachment).
I would like to know if there is a way to set the net to use the segmentation map as a "hint" and not as a strict constraint (from the attachment you can clearly tell where are the bounds of the segmentation map).

Thank you.

![zing_cat5_encoder](https://user-images.githubusercontent.com/4083396/67687589-d24b3480-f998-11e9-88f9-6d37e4e9ab62.png)

**Comment by jaejun-yoo** [comment]
Hi, thank you for your interest! 
This happens because our network is designed to precisely preserve every structure of the given image. 
Thus, an easy solution would be to relax the network. 
What happens if you try **summed version** for unpooling instead of concatenating version ? I think that will relax this issue a little. 
The other thing you can try would be to blend the styles at the mask boundary during the stylizing operation of the feed forward process. 

Still, I would not say that these can entirely solve the problem. 
In fact, your question is very important and it is closely related to one of the core problems in the field; finding a natural correspondence between arbitrary images. 

I hope my answer was helpful. If you still want to discuss please feel free to comment! thx :)

---
If you find this project is useful or interesting, please consider ⭐️ and watch our repo. Thanks!
