### ISSUE TITLE
In "cat5" skip network, only the last layer matters

### ISSUE THREAD

**Issue by wanghxcis** [clovaai/WCT2#17]
Thank you for your great work. In the skip decoder network, I try to test just one layer with wct and find only the last layer matters. The other layers seem to contribute little to the final result. It seems the skip structure just bypass the normal flow, am I right?

**Comment by jaejun-yoo** [comment]
@wanghxcis Thank you for your interest! Yes, you are right. Since the cat5 version breaks the theoretical condition and provides more freedom to the network, it is indeed the skip structure that gives the most powerful effect on the output stylization. I think this would happen less in the sum version. You can also try to constrain the network not to ignore the lower path by imposing an auxiliary loss in the intermediate embedding spaces.  

---
If you find this project is useful or interesting, please consider ⭐️ and watch our repo. Thanks!

**Comment by wanghxcis** [comment]
Thanks for your kindly answer!
