### ISSUE TITLE
QS about the depth map of transfered images

### ISSUE THREAD

**Issue by Jemmagu** [clovaai/WCT2#22]
Hi @jaejun-yoo , thank you for your great work!

I have some original images and their corresponding depth maps. I wanna ask that after getting the style-transfered images, could the original depth maps still match them? Namely, will the style-transfer process induces a minor depth offset?

Big thanks!

**Comment by jaejun-yoo** [comment]
Dear @Jemmagu 
Thank you for your interest in our paper! Um frankly, I have not tried that so I am not sure about the consequences. 
Still, if I try to guess, my short answer is (ideally) 'no' it should not induce any depth offset but (practically) 'yes' dependent on the performance of the depth estimation model. 

Below is my thought process:
If the depth estimation model works ideally, its result should remain the same whether or not the style is changed, e.g., the depth map should not change just because the time changed from day to night. However, the lightings and other aspects of the style that are newly imposed on the image would cause confusion to the depth estimation model, e.g., if it is too dark, you cannot distinguish the depth. 

In practice, most probably, if I test this, the consequence would be yes that it induces a minor (or even a major) depth offset and the magnitude of change will depend on the style image you use. 

This was quite an interesting question to think of. Thanks for your question again and I would love to hear what happens if you try. 

Best, 
Jaejun
