### ISSUE TITLE
How does it work for an indoor dataset?

### ISSUE THREAD

**Issue by RJ2702** [clovaai/WCT2#25]
I have an indoor dataset where the goal is to take the texture of one furniture and overlay on a similar furniture in another room setup. When I directly run this code, the color gets transferred but not the exact texture. Is there any paramater I should tweak to get the desired output? Can you shed some light on this?

**Comment by jaejun-yoo** [comment]
Hi, I am not sure what would help this. However, if you want to apply more texture, there is one thing I have tried. Since WCT and WCT2 have the same architecture (except the wavelet pooling and unpooling parts), what you may do is to mix the original WCT layers and WCT2 layers. This would give some intermediate results between the artistic and photorealistic stylization.
