### ISSUE TITLE
LL components vs. avg. pooling

### ISSUE THREAD

**Issue by felixplum** [clovaai/WCT2#27]
Hi, 

in the original paper equivalence between avg. pooling and the LL-component of the decomposition are claimed. However, in your code the L-component evaluates to [[0.5, 0.5], [0.5, 0.5]], which contradicts this statement. Am I missing something?

**Comment by jaejun-yoo** [comment]
Hi, we did not mean to say that LL is exactly the average pooling. We are saying that it is giving a similar effect (extracting a DC component of an image) to what average pooling does, and it actually is with a constant factor of 1/2 in that the average pooling is 1/2 * [[0.5,0.5], [0.5,0.5]]. The constant factor can be ignored since this operation is combined with the learned weights.

**Comment by felixplum** [comment]
Thanks for the quick answer, that makes sense!
